---
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'utf-8'
    layout: 'default'
    title: 'Scroll'
- scope:
    path: ''
    type: 'authors'
  values:
    encoding: 'utf-8'
    layout: 'author'
    title: 'Author'
- scope:
    path: ''
    type: 'chapters'
  values:
    encoding: 'utf-8'
    layout: 'default'
    title: 'Scroll'
- scope:
    path: ''
    type: 'stories'
  values:
    encoding: 'utf-8'
    layout: 'story'
    title: 'Story'
collections_dir: _data
collections:
  authors:
    output: true
    sort_by: slug
  chapters:
    output: true
    sort_by: slug
  stories:
    output: true
    sort_by: slug
